### ISSUE TITLE
Start only allows one option

### ISSUE THREAD

**Issue by marquiswang** [Homebrew/homebrew-autoupdate#121]
Running start with multiple options:

```
brew autoupdate start 86400 --upgrade –-sudo
```

leads to the error:
```
Error: Invalid usage: This subcommand does not take more than 1 named argument.
```

But there are definitely use cases when you might want multiple options. `--upgrade --sudo --immediate --cleanup`, etc.

**Comment by swissbuechi** [comment]
The command `brew autoupdate start 86400 --upgrade --sudo` works fine for me.

You are right, I actually recommend running the following combination:
`brew autoupdate start 86400 --upgrade --cleanup --immediate --sudo`

When I copy and paste your command from above, I somehow get the same error as you. I think there is some strange character in yours. I will try to figure it out.

Update:
Got it, you used `-` instead of `-` in the `--sudo` argument.
This issue can be closed.

**Comment by marquiswang** [comment]
Oh god, how embarrassing. I copy/pasted from somewhere with bad formatting. Closing.
