### ISSUE TITLE
Also update mas (App Store apps)

### ISSUE THREAD

**Issue by honeybyhomo** [Homebrew/homebrew-autoupdate#127]
Is there a reason it doesn't update mas apps – or has an option (--upgrademas) to do so?

Oh, and I frickin' LOVE Homebrew and Autoupdate!

**Comment by swissbuechi** [comment]
Could you please provide the brew commands you use to upgrade the mas apps manually?

Thanks

**Comment by simongade** [comment]
Of course!
`mas upgrade`

**Comment by swissbuechi** [comment]
> Of course! `mas upgrade`

I've never used`mas`, but it seems like there is an integration between `homebrew-bundle` and the `mas-cli`.
As far as I understand, you can bundle `mas` dependencies inside your `Brewfile` to automatically install them when running `brew bundle <Brewfile>`.

Is there any other integration between `mas` and `brew`, which I may have missed?

Of course, it would not very difficult to implement running `mas upgrade` when executing `homebrew-autoupdate`, but I don't know if we're supposed to mix these projects together.

**Comment by simongade** [comment]
I guess I always thought of it as integrated into brew (probably because it's included in brewfile) but I guess technically it is separate.
It seems strange _not_ to include updating those apps in autoupdate in my opinion. I install all apps (including from App Store) from Brew – naturally I want to update them all as well.
Don't know who to ask "permission" to include it in autoupdate.

**Comment by swissbuechi** [comment]
> I install all apps (including from App Store) from Brew

What command do you run to achieve this?
Don't you use the `mas-cli`?
```Bash
mas install 409183694   # Keynote
```

Or do you run `brew bundle <Brewfile>`?

**Comment by simongade** [comment]
I use `brew bundle <Brewfile>`

**Comment by swissbuechi** [comment]
Alright.
Technically, there seems to be no difference if a Store app was installed using `brew bundle` or `mas install`.

In terms of auto-updates, aren't the `mas` installed apps also detected as `installed` in your App Store? And wouldn't they just automatically update by itself, like any other app installed through the App Store?
If this is the case, it would not make sense to include `mas` in `homebrew-autoupdate`.
Otherwise, this may be worth a thought.

**Comment by simongade** [comment]
"Regular" apps also automatically update by itself (at some point) – one of the points of Brew (and autoupdate) is that we decide to update _now_  and not when the system decides to.

**Comment by swissbuechi** [comment]
> "Regular" apps also automatically update by itself (at some point)

This is not true for homebrew formulae, these are simple ruby scripts which never automatically update.
And in the case of Casks, only the ones with `auto_updates true` configured, have a built-in auto update feature.

> one of the points of Brew (and autoupdate) is that we decide to update now and not when the system decides to.

You could pass `--greedy` to ether `brew upgrade` or `brew autoupdate start --upgrade ...` to include the applications, which would normally only be updated using the built-in update mechanism. You would need to manually disable the built-in updates for every Cask you install.

I really prefer the built-in upgrade mechanism. In most cases, the user experience benefits compared to the `--greedy` enforced upgrades. For example, in Microsoft Edge, you'll get a nice notification that indicates a pending restart due to an upgrade.

Anyway, do you know if applications installed with `mas-cli` still automatically update thought the App Store or not?

**Comment by simongade** [comment]
I'm not 100% sure but I do believe that App Store apps installed via `mas-cli` update through the App Store.

Just to understand: Would adding a `--include-mas` option be bad in any way? Those that don't want to use it don't include it and those that do can use it.

And thanks for the discussion – I'm fairly new to github and all the great software on here – pretty amazing.

**Comment by MikeMcQuaid** [comment]
> I'm not 100% sure but I do believe that App Store apps installed via `mas-cli` update through the App Store.

They do, yes. 



> Just to understand: Would adding a `--include-mas` option be bad in any way? Those that don't want to use it don't include it and those that do can use it.

Depends how much code is needed to maintain and how many people want to use it.

I tend to agree with @swissbuechi that there's little value adding something that can be done automatically by macOS for you.
